# 03
# What is the amount of flow $x$ emitted as output during the time period $y$ ?

Select ?x where {
?x a b:flow;
   b:flowOf ?z;
   b:hasTemporalExtent ?y.
?z a b:flow-object.
?y b:hasBeginning ?low;
   b:hasEnd ?up}
