# 05
# What other agents performing the same type of activity of agent $z$ are present in the same location $w$?

Select ?a where {
z a b:agent;
  b:performs ?w;
  b:location ?l.
?y b:performs ?w;
   b:location ?l.
Minus { z }
}
